### ISSUE TITLE
Social Share mailto bug

### ISSUE THREAD

**Issue by gyulanemeth** [EDMdesigner/email-html-generator-issues#11]
Hi all,

we found a bug when create a forward with social share.

The html generated is

<a
href="mailto:##emailToSend##?&body=%23%23textToShare%23%23%3A%20%23%23linkToShare%23%23"
class="edm_button" style="text-decoration: none;">

on outlook not work properly because the '&' before body params is present.

Please check it.

Best regards
## 

Alessandro Rovito
Developer

**Comment by gyulanemeth** [comment]
Hello, what was the original link?

**Comment by gyulanemeth** [comment]
I have checked the issue, and it seems like the subject query string param is missing from the social share element. Actually it's coming from the editor side. There I can replace it to this:
mailto:##emailToSend##?title=##text##&body=##text##:%20##link##

Would that be okay?

**Comment by m33ch** [comment]
the problem is not about the subject, actually the button add the "view on browser url" in the body of the email, and an empty subject. This is correct.
The problem is that outlook doesn't understand the mailto link.

In the image 1 you can see the link
In the image 2 you can see the resulting email.

In other email clients the link work good, creating an email with a link in the body.

![1](https://cloud.githubusercontent.com/assets/1915008/16563036/255ac004-4200-11e6-8edb-a9760e0742ce.png)
![2](https://cloud.githubusercontent.com/assets/1915008/16563034/2545fd18-4200-11e6-83e4-130cdd82d908.png)

**Comment by gyulanemeth** [comment]
Yes, but as far as I can see it could happen because by mistake there was no subject part in the link.

We can do two things:
1) We add the subject part, so the link will look like this:
    mailto:##emailToSend##?subject=##text##&body=##text##:%20##link##
    This way the subject line will be filled automatically with the value you replaced ##text## with
2) We simply delete the & sign from the link, so it will look like this:
    mailto:##emailToSend##?body=##text##:%20##link##
   But this way the subject line won't be filled.

I think the 1st option is better. What do you think?

**Comment by m33ch** [comment]
I also think that the first solution is the best.

Thank you

**Comment by gyulanemeth** [comment]
It is fixed and deployed. The users who had problems with the social share element might need to change the layout of the social share element and change it back to  fix the problem with the link. Also, they might need a hard refresh while they are using the editor.
