### ISSUE TITLE
Firefox - gmail bug

### ISSUE THREAD

**Issue by Silassiai** [EDMdesigner/email-html-generator-issues#27]
The newsletter doen not work on firefox in gmail properly.
It does not show some prices, i changed the boxes to buttons but this did not solve the problem. 

Can you guys please take a look?

![screenshot_14](https://cloud.githubusercontent.com/assets/18419961/26299204/4ab7c0d6-3eda-11e7-8c6c-a3fde558b1c1.png)

[591d17229ed2cb6c6e194aa2.txt](https://github.com/EDMdesigner/email-html-generator-issues/files/1018157/591d17229ed2cb6c6e194aa2.txt)

**Comment by smiska** [comment]
Hi, thanks for sharing this.
We started to investigate the possible cause,
but couldn't find the solution yet. 
I'll keep you in the loop with any updates.

**Comment by smiska** [comment]
Hi Silassiai, 

I checked the template with Litmus and it seems that there's really something wrong in Gmail Firefox. 
I don't know what might be the problem, but we had a very similar one last year.

@Greg is the expert with issues like this, but the fix is complicated usually (since it has to do sg with the generator or your specific template structure).

If it is possible, I would advise you to simplify the template, remove a couple of boxes which are not necessary. Sometimes complicated templates, with a large amount of embedded boxes can behave in strange ways.

**Comment by smiska** [comment]
Hi, 

Greg provided me with the screenshot below. The screenshot shows the inspected Gmail test email.  After a certain level (quite high level) of complexity, gmail is not able to display the nested elements. I examined the source code of the preview that our app generates and it doesn't have the empty table without dimensions. So this bug should be resolved with a simpler template with less box elements (less nested tables) that gmail can also handle.
![image](https://cloud.githubusercontent.com/assets/16736043/26494519/5516ee92-421f-11e7-9eb2-33a07d2168f1.png)
